### ISSUE TITLE
Gitlab and Sentry?

### ISSUE THREAD

**Issue by nigeldunn** [desdrury/k8sdc#6]
Hi Des,

Curious if you've looked into Gitlab for SCM in addition to offering a bunch of other features. Also Sentry (https://getsentry.com/) for exception logging? I'm looking at both of these for my personal stuff and thought I'd see if you've considered them at all.

Cheers,
Nigel.

**Comment by desdrury** [comment]
Hi Nigel,

Gitlab is definitely on the roadmap.  It really looks good and the recent introduction of a Docker Registry is very cool.  Sentry wasn't on the roadmap but I am aware of it and it does look really promising as well.  In fact I reckon it should be on the roadmap!  Fancy incorporating it into k8sdc?

You might notice that not many products have been integrated into k8sdc recently.  Thats because I've held back making a commitment to a Kubernetes package manager until I could make a clear decision between KPM and Helm.  KPM looked promising, but now that the Helm 2 architecture is taking shape, with the recent release of the first Alpha, I think I'll probably go down that route.

Cheers.

Des
